language: node_js

node_js:
  - '10'

addons:
  chrome: stable
# http://karma-runner.github.io/1.0/plus/travis.html
# https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-directly
before_script:
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - sleep 3 # give xvfb some time to start
